pipeline {
    agent any

    environment {
        SERVER_IP = 'server ip'
    }

    stages {

        stage('Set parameter') {
            steps {
                script {
                    withAWS(region: 'ap-northeast-2', credentials: 'JenkinsUser'){
                        env.SERVER_IP = sh(script: "aws ssm get-parameters --name /front/SERVER_IP | jq -j '.Parameters[0].Value'", returnStdout: true)
                    }
                }
            }
            post {
                success {
                    slackSend (channel: 'frontch', color: '#00FF20', message: "get parameter finished - '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
                failure {
                    slackSend (channel: 'frontch', color: '#FF0040', message: "get parameter failed - '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
            }
        }

        stage('Build'){
            steps {
                sh 'yarn install --network-timeout 600000000 --production'
                sh 'yarn build'
            }
            post {
                success {
                    slackSend (channel: 'frontch', color: '#00FF20', message: "npm build ended successfully - '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
                failure {
                    slackSend (channel: 'frontch', color: '#FF0040', message: "npm build failed - '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
            }
        }
        stage('Deploy React') {
            steps {
                sh 'sudo cp -rf /var/lib/jenkins/workspace/ANFrontPipeline_master/build/* /var/www/build/*'
                sh 'sudo service nginx restart'
            }
            post {
                success {
                    slackSend (channel: 'frontch', color: '#00FF20', message: "Deploy ended successfully - '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
                failure {
                    slackSend (channel: 'frontch', color: '#FF0040', message: "Deploy failed - '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
            }
        }
    }
}